name: Build & Test Bio-tracker Node App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  node-version: '18.x'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: bahmutov/npm-install@v1
    - run: npm i
    - name: Use Node.js $node-version
      uses: actions/setup-node@v3
      with:
        node-version: $node-version
        cache: 'npm'
    - run: npm run build-only --if-present
