name: Build & Test Bio-tracker Node App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  node-version: '18.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm i
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    - run: npm run build --if-present

    - name: Update version
      run: |
        git status
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"
        npm version patch
        VERSION=$(node -p "require('./package.json').version")
        git tag ${VERSION}
        git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@$GITHUB_REPOSITORY.git" --follow-tags
